# Nexus Metalcraft Configuration
[project]
name = "doxoade"
version = "1.0.0"
type = "executable"

[compiler]
engine = "gcc"
std = "c11"
opt = "O2"
shield = true         # Ativa Sotéria (Resgate Nativo)
incremental = true    # Recompila apenas mudanças

[paths]
sources = ["src/*.c"]
headers = ["include/"]
output  = "bin/"

# Adicione este target ao seu arquivo existente
[[targets]]
name = "gordian_test"
sources = ["doxoade/experiments/soteria_lab/gordian_lab.c"]
output = "bin/gordian_test.exe"