# -*- coding: utf-8 -*-
# doxoade/tools/lua_systems/lua_bridge.py
"""
🪽 HERMES LUA BRIDGE — Motor de Serialização e Interoperabilidade Python <-> Lua.
Converte estruturas de dados Python (dict, list, primitivos) em tabelas Lua canônicas
para consumo de altíssima performance via `dofile` no Lite XL e outros nós Lua.
"""
from __future__ import annotations
import os
from pathlib import Path
from typing import Any, Union


def python_to_lua(data: Any, indent_level: int = 0, indent_str: str = "  ") -> str:
    """Serializa estruturas de dados Python em literais de tabela Lua válidos."""
    curr_indent = indent_str * indent_level
    next_indent = indent_str * (indent_level + 1)

    if data is None:
        return "nil"
    if isinstance(data, bool):
        return "true" if data else "false"
    if isinstance(data, (int, float)):
        return str(data)
    if isinstance(data, str):
        escaped = (
            data.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
        )
        return f'"{escaped}"'
    if isinstance(data, (list, tuple, set)):
        if not data:
            return "{}"
        items = [
            f"{next_indent}{python_to_lua(item, indent_level + 1, indent_str)}"
            for item in data
        ]
        return "{\n" + ",\n".join(items) + f"\n{curr_indent}}}"
    if isinstance(data, dict):
        if not data:
            return "{}"
        entries = []
        for k, v in data.items():
            k_str = str(k)
            if k_str.isidentifier() and not k_str.startswith("_"):
                key_repr = k_str
            else:
                key_repr = f'["{k_str}"]'
            val_repr = python_to_lua(v, indent_level + 1, indent_str)
            entries.append(f"{next_indent}{key_repr} = {val_repr}")
        return "{\n" + ",\n".join(entries) + f"\n{curr_indent}}}"

    escaped = str(data).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_lua_bridge_file(
    file_path: Union[str, Path], data: Any, return_export: bool = True
) -> Path:
    """Grava um arquivo .lua de forma atômica com cabeçalho padrão de integridade."""
    p = Path(file_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    temp_file = p.with_suffix(f".tmp_{os.getpid()}")

    lua_table_str = python_to_lua(data, indent_level=0)
    prefix = "-- ⚡ Auto-generated by Doxoade Hermes Lua Bridge\n"
    if return_export:
        content = f"{prefix}return {lua_table_str}\n"
    else:
        content = f"{prefix}{lua_table_str}\n"

    temp_file.write_text(content, encoding="utf-8")
    temp_file.replace(p)
    return p
