# -*- coding: utf-8 -*-
# doxoade/tools/lua_systems/api_guard/api_catalog.py
"""
Catálogo Soberano de APIs do Lite XL — Doxoade Nexus Edition.
Capítulo 2: Schema unificado, semente de contratos e persistência JSON/Lua.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Dict, List, Optional, Any, Union


@dataclass
class APIEntry:
    id: str                                # Ex: "RootView.on_text_input" ou "core.open_doc"
    kind: str                              # "module" | "class" | "method" | "function" | "field" | "event_handler"
    module: str                            # Ex: "core.rootview", "core", "system"
    name: str                              # Ex: "on_text_input"
    expected_type: str = "function"        # "function" | "table" | "string" | "number" | "boolean"
    cls_name: Optional[str] = None         # Ex: "RootView", "Doc", "Node"
    severity_if_missing: str = "critical"  # "critical" | "warning" | "info"
    safe_to_patch: bool = False            # Se o Doxoade pode aplicar monkey-patch com segurança
    is_deprecated: bool = False            # Se a API é obsoleta/deprecada em versões novas
    fallback: Optional[str] = None         # Nome ou estratégia de fallback (ex: "Doc.text_input")
    signature_notes: str = ""              # Detalhes de argumentos e retornos esperados
    known_consumers: List[str] = field(default_factory=list)  # Quais templates utilizam

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> APIEntry:
        valid_keys = {k for k in cls.__dataclass_fields__}
        filtered = {k: v for k, v in data.items() if k in valid_keys}
        return cls(**filtered)


class APICatalogSchema:
    """Serializador e validador de integridade do catálogo."""

    SCHEMA_VERSION = "2.0.0"

    @classmethod
    def serialize_json(cls, catalog: Dict[str, APIEntry], indent: int = 2) -> str:
        payload = {
            "version": cls.SCHEMA_VERSION,
            "total_entries": len(catalog),
            "apis": {k: v.to_dict() for k, v in sorted(catalog.items())}
        }
        return json.dumps(payload, indent=indent, ensure_ascii=False)

    @classmethod
    def deserialize_json(cls, json_str: str) -> Dict[str, APIEntry]:
        data = json.loads(json_str)
        apis: Dict[str, APIEntry] = {}
        for k, v in data.get("apis", {}).items():
            apis[k] = APIEntry.from_dict(v)
        return apis

    @classmethod
    def export_to_lua(cls, catalog: Dict[str, APIEntry]) -> str:
        """Gera uma tabela Lua soberana consumível diretamente por api_probe e api_guard."""
        def to_lua_val(val: Any) -> str:
            if val is None:
                return "nil"
            elif isinstance(val, bool):
                return "true" if val else "false"
            elif isinstance(val, (int, float)):
                return str(val)
            else:
                return json.dumps(str(val))

        lines = [
            "-- auto-generated by doxoade api_catalog.py",
            "return {",
            f'  schema_version = "{cls.SCHEMA_VERSION}",',
            f"  total_apis = {len(catalog)},",
            "  catalog = {"
        ]
        for api_id, entry in sorted(catalog.items()):
            lines.append(f'    ["{api_id}"] = {{')
            lines.append(f'      kind = "{entry.kind}",')
            lines.append(f'      module = "{entry.module}",')
            lines.append(f'      name = "{entry.name}",')
            lines.append(f'      expected_type = "{entry.expected_type}",')
            lines.append(f'      cls_name = {to_lua_val(entry.cls_name)},')
            lines.append(f'      severity = "{entry.severity_if_missing}",')
            lines.append(f'      safe_to_patch = {"true" if entry.safe_to_patch else "false"},')
            lines.append(f'      is_deprecated = {"true" if entry.is_deprecated else "false"},')
            lines.append(f'      fallback = {to_lua_val(entry.fallback)},')
            lines.append("    },")
        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)


def get_api_guard_dir(user_dir: Optional[Path] = None) -> Path:
    """Retorna e garante o diretório padrão de artefatos do API Guard."""
    if user_dir is None:
        try:
            from doxoade.commands.lite_xl_systems.engine_lite_xl import LiteXLEngine
            user_dir = LiteXLEngine.get_user_dir()
        except Exception:
            user_dir = Path.home() / ".config" / "lite-xl"

    guard_dir = user_dir / ".doxoade" / "api_guard"
    guard_dir.mkdir(parents=True, exist_ok=True)
    (guard_dir / "reports").mkdir(exist_ok=True)
    (guard_dir / "quarantine").mkdir(exist_ok=True)
    return guard_dir

def get_default_catalog() -> Dict[str, APIEntry]:
    """Retorna o catálogo semente com todas as APIs mapeadas do Lite XL e Doxoade."""
    entries: List[APIEntry] = [
        # ==========================================
        # MÓDULOS BASE
        # ==========================================
        APIEntry(
            id="rencache",                     # ← era "core.rencache"
            kind="module",
            module="_G",                        # ← global, não core.*
            name="rencache",
            expected_type="table",
            severity_if_missing="warning",
            fallback="renderer",
            signature_notes="Global _G.rencache (polyfill cobre require core.rencache).",
            known_consumers=["03_tab_colors.lua", "04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="core",
            kind="module",
            module="core",
            name="core",
            expected_type="table",
            severity_if_missing="critical",
            safe_to_patch=False,
            signature_notes="Motor principal do Lite XL.",
            known_consumers=["all"],
        ),
        APIEntry(
            id="core.common",
            kind="module",
            module="core.common",
            name="common",
            expected_type="table",
            severity_if_missing="critical",
            signature_notes="Utilitários comuns e fuzzy match.",
            known_consumers=["06_tree_manager.lua", "14_doxnote_panel.lua"],
        ),
        APIEntry(
            id="core.config",
            kind="module",
            module="core.config",
            name="config",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["02_blacklist.lua", "04_color_and_search_highlight.lua", "13_toolbar_doxoade.lua"],
        ),
        APIEntry(
            id="core.style",
            kind="module",
            module="core.style",
            name="style",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["03_tab_colors.lua", "11_tab_context_menu.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="core.command",
            kind="module",
            module="core.command",
            name="command",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["all"],
        ),
        APIEntry(
            id="core.keymap",
            kind="module",
            module="core.keymap",
            name="keymap",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["07_keymaps_and_help.lua", "12_ui_forge.lua"],
        ),
        APIEntry(
            id="core.node",
            kind="module",
            module="core.node",
            name="Node",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["03_tab_colors.lua", "05_split_mover.lua", "11_tab_context_menu.lua"],
        ),
        APIEntry(
            id="core.docview",
            kind="module",
            module="core.docview",
            name="DocView",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["04_color_and_search_highlight.lua", "08_pot_panel.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="core.doc",
            kind="module",
            module="core.doc",
            name="Doc",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="core.view",
            kind="module",
            module="core.view",
            name="View",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["12_ui_forge.lua"],
        ),
        APIEntry(
            id="core.rootview",
            kind="module",
            module="core.rootview",
            name="RootView",
            expected_type="table",
            severity_if_missing="critical",
            known_consumers=["01_ipc_dispatcher.lua", "11_tab_context_menu.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="core.statusview",
            kind="module",
            module="core.statusview",
            name="StatusView",
            expected_type="table",
            severity_if_missing="warning",
            known_consumers=["13_toolbar_doxoade.lua"],
        ),
        APIEntry(
            id="core.syntax",
            kind="module",
            module="core.syntax",
            name="syntax",
            expected_type="table",
            severity_if_missing="warning",
            known_consumers=["04_color_and_search_highlight.lua", "08_pot_panel.lua"],
        ),
        APIEntry(
            id="renderer",
            kind="module",
            module="renderer",
            name="renderer",
            expected_type="table",
            severity_if_missing="warning",
            fallback="core.rencache",
            signature_notes="API nativa C de desenho.",
            known_consumers=["03_tab_colors.lua", "04_color_and_search_highlight.lua", "11_tab_context_menu.lua"],
        ),
        APIEntry(
            id="core.rencache",
            kind="module",
            module="core.rencache",
            name="rencache",
            expected_type="table",
            severity_if_missing="warning",
            fallback="renderer",
            signature_notes="Render Cache System do Lite XL.",
            known_consumers=["03_tab_colors.lua", "04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="system",
            kind="module",
            module="system",
            name="system",
            expected_type="table",
            severity_if_missing="critical",
            signature_notes="API global C de sistema de arquivos e SO.",
            known_consumers=["all"],
        ),

        # ==========================================
        # FUNÇÕES GLOBAIS / CORE DISPATCH
        # ==========================================
        APIEntry(
            id="core.open_doc",
            kind="function",
            module="core",
            name="open_doc",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="core.open_doc([filename]) -> Doc",
            known_consumers=["06_tree_manager.lua", "07_keymaps_and_help.lua", "08_pot_panel.lua"],
        ),
        APIEntry(
            id="core.set_active_view",
            kind="function",
            module="core",
            name="set_active_view",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="core.set_active_view(view)",
            known_consumers=["05_split_mover.lua", "08_pot_panel.lua", "09_panel_manager.lua"],
        ),
        APIEntry(
            id="core.add_project_directory",
            kind="function",
            module="core",
            name="add_project_directory",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="core.add_project_directory(path)",
            known_consumers=["06_tree_manager.lua", "10_forensic_engine.lua"],
        ),
        APIEntry(
            id="core.remove_project_directory",
            kind="function",
            module="core",
            name="remove_project_directory",
            expected_type="function",
            severity_if_missing="warning",
            signature_notes="core.remove_project_directory(path_or_item)",
            known_consumers=["06_tree_manager.lua"],
        ),
        APIEntry(
            id="core.add_thread",
            kind="function",
            module="core",
            name="add_thread",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="core.add_thread(fn, target)",
            known_consumers=["10_forensic_engine.lua", "13_toolbar_doxoade.lua"],
        ),
        APIEntry(
            id="core.log",
            kind="function",
            module="core",
            name="log",
            expected_type="function",
            severity_if_missing="info",
            signature_notes="core.log(fmt, ...)",
            known_consumers=["all"],
        ),
        APIEntry(
            id="core.error",
            kind="function",
            module="core",
            name="error",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=True,
            signature_notes="core.error(fmt, ...)",
            known_consumers=["06_tree_manager.lua", "10_forensic_engine.lua"],
        ),
        APIEntry(
            id="core.command.add",
            kind="function",
            module="core.command",
            name="add",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="command.add(predicate_or_nil, map_of_commands)",
            known_consumers=["all"],
        ),
        APIEntry(
            id="core.command.perform",
            kind="function",
            module="core.command",
            name="perform",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="command.perform(command_name, ...)",
            known_consumers=["06_tree_manager.lua", "13_toolbar_doxoade.lua"],
        ),
        APIEntry(
            id="core.keymap.add",
            kind="function",
            module="core.keymap",
            name="add",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="keymap.add(map_of_keys)",
            known_consumers=["07_keymaps_and_help.lua", "12_ui_forge.lua"],
        ),

        # ==========================================
        # ROOTVIEW & EVENT HANDLERS (ZONA DE RISCO)
        # ==========================================
        APIEntry(
            id="RootView.draw",
            kind="method",
            module="core.rootview",
            cls_name="RootView",
            name="draw",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="RootView:draw()",
            known_consumers=["11_tab_context_menu.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="RootView.on_mouse_moved",
            kind="event_handler",
            module="core.rootview",
            cls_name="RootView",
            name="on_mouse_moved",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=True,
            signature_notes="RootView:on_mouse_moved(x, y, dx, dy)",
            known_consumers=["11_tab_context_menu.lua"],
        ),
        APIEntry(
            id="RootView.on_mouse_pressed",
            kind="event_handler",
            module="core.rootview",
            cls_name="RootView",
            name="on_mouse_pressed",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=True,
            signature_notes="RootView:on_mouse_pressed(button, x, y, clicks)",
            known_consumers=["11_tab_context_menu.lua"],
        ),
        APIEntry(
            id="RootView.on_text_input",
            kind="event_handler",
            module="core.rootview",
            cls_name="RootView",
            name="on_text_input",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=False,
            is_deprecated=True,
            fallback="DocView.on_text_input",
            signature_notes="DEPRECADA em versões recentes do Lite XL. O input de texto foi transferido para Views específicas.",
            known_consumers=["07_keymaps_and_help.lua (antigo)"],
        ),
        APIEntry(
            id="RootView.on_key_pressed",
            kind="event_handler",
            module="core.rootview",
            cls_name="RootView",
            name="on_key_pressed",
            expected_type="function",
            severity_if_missing="info",         # ← era "warning"
            safe_to_patch=True,
            signature_notes="Inexistente no Lite XL; teclado é via keymap/core.on_event.",
            known_consumers=["07_keymaps_and_help.lua"],
        ),

        # ==========================================
        # NODE & TAB RENDERING
        # ==========================================
        APIEntry(
            id="Node.draw_tab_title",
            kind="method",
            module="core.node",
            cls_name="Node",
            name="draw_tab_title",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="Node:draw_tab_title(view, font, is_active, is_hovered, x, y, w, h)",
            known_consumers=["03_tab_colors.lua"],
        ),
        APIEntry(
            id="Node.split",
            kind="method",
            module="core.node",
            cls_name="Node",
            name="split",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Node:split(dir, view, locked, inherit_size)",
            known_consumers=["01_ipc_dispatcher.lua", "05_split_mover.lua", "08_pot_panel.lua", "09_panel_manager.lua"],
        ),
        APIEntry(
            id="Node.add_view",
            kind="method",
            module="core.node",
            cls_name="Node",
            name="add_view",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Node:add_view(view, idx)",
            known_consumers=["05_split_mover.lua", "08_pot_panel.lua", "09_panel_manager.lua"],
        ),
        APIEntry(
            id="Node.get_view_idx",
            kind="method",
            module="core.node",
            cls_name="Node",
            name="get_view_idx",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Node:get_view_idx(view) -> integer",
            known_consumers=["05_split_mover.lua"],
        ),
        APIEntry(
            id="Node.on_mouse_pressed",
            kind="event_handler",
            module="core.node",
            cls_name="Node",
            name="on_mouse_pressed",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=True,
            signature_notes="Node:on_mouse_pressed(button, x, y, clicks)",
            known_consumers=["11_tab_context_menu.lua"],
        ),

        # ==========================================
        # DOC & BUFFER MANIPULATION
        # ==========================================
        APIEntry(
            id="Doc.insert",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="insert",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="Doc:insert(line, col, text)",
            known_consumers=["04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="Doc.remove",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="remove",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="Doc:remove(line1, col1, line2, col2)",
            known_consumers=["04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="Doc.save",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="save",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="Doc:save(filename, temp_filename)",
            known_consumers=["04_color_and_search_highlight.lua"],
        ),
        APIEntry(
            id="Doc.get_selection",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="get_selection",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Doc:get_selection(sort) -> l1, c1, l2, c2",
            known_consumers=["01_ipc_dispatcher.lua", "04_color_and_search_highlight.lua", "07_keymaps_and_help.lua"],
        ),
        APIEntry(
            id="Doc.has_selection",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="has_selection",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Doc:has_selection() -> boolean",
            known_consumers=["04_color_and_search_highlight.lua", "07_keymaps_and_help.lua"],
        ),
        APIEntry(
            id="Doc.get_text",
            kind="method",
            module="core.doc",
            cls_name="Doc",
            name="get_text",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="Doc:get_text(l1, c1, l2, c2) -> string",
            known_consumers=["04_color_and_search_highlight.lua", "07_keymaps_and_help.lua"],
        ),

        # ==========================================
        # DOCVIEW & RENDERING
        # ==========================================
        APIEntry(
            id="DocView.draw_line_gutter",
            kind="method",
            module="core.docview",
            cls_name="DocView",
            name="draw_line_gutter",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="DocView:draw_line_gutter(line_idx, x, y, width) -> number",
            known_consumers=["04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="DocView.draw_line_body",
            kind="method",
            module="core.docview",
            cls_name="DocView",
            name="draw_line_body",
            expected_type="function",
            severity_if_missing="critical",
            safe_to_patch=True,
            signature_notes="DocView:draw_line_body(line_idx, x, y) -> number",
            known_consumers=["04_color_and_search_highlight.lua", "15_audit_highlighter.lua"],
        ),
        APIEntry(
            id="DocView.get_gutter_width",
            kind="method",
            module="core.docview",
            cls_name="DocView",
            name="get_gutter_width",
            expected_type="function",
            severity_if_missing="warning",
            safe_to_patch=True,
            signature_notes="DocView:get_gutter_width() -> number",
            known_consumers=["04_color_and_search_highlight.lua"],
        ),

        # ==========================================
        # STATUSVIEW & COMMANDVIEW
        # ==========================================
        APIEntry(
            id="StatusView.add_item",
            kind="method",
            module="core.statusview",
            cls_name="StatusView",
            name="add_item",
            expected_type="function",
            severity_if_missing="warning",
            signature_notes="Suporta tanto a assinatura antiga por parâmetros quanto a nova por tabela spec.",
            known_consumers=["13_toolbar_doxoade.lua"],
        ),
        APIEntry(
            id="core.command_view.enter",
            kind="method",
            module="core.commandview",
            cls_name="CommandView",
            name="enter",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="core.command_view:enter(text, callbacks)",
            known_consumers=["06_tree_manager.lua", "07_keymaps_and_help.lua"],
        ),

        # ==========================================
        # SYSTEM NATIVE C-LEVEL
        # ==========================================
        APIEntry(
            id="system.absolute_path",
            kind="function",
            module="system",
            name="absolute_path",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="system.absolute_path(path) -> string",
            known_consumers=["all"],
        ),
        APIEntry(
            id="system.mkdir",
            kind="function",
            module="system",
            name="mkdir",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="system.mkdir(path) -> boolean",
            known_consumers=["all"],
        ),
        APIEntry(
            id="system.get_file_info",
            kind="function",
            module="system",
            name="get_file_info",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="system.get_file_info(path) -> table|nil",
            known_consumers=["all"],
        ),
        APIEntry(
            id="system.list_dir",
            kind="function",
            module="system",
            name="list_dir",
            expected_type="function",
            severity_if_missing="critical",
            signature_notes="system.list_dir(path) -> table|nil",
            known_consumers=["06_tree_manager.lua", "14_doxnote_panel.lua"],
        ),
        APIEntry(
            id="system.set_clipboard",
            kind="function",
            module="system",
            name="set_clipboard",
            expected_type="function",
            severity_if_missing="warning",
            signature_notes="system.set_clipboard(text)",
            known_consumers=["11_tab_context_menu.lua", "12_ui_forge.lua"],
        ),
        APIEntry(
            id="system.show_in_file_manager",
            kind="function",
            module="system",
            name="show_in_file_manager",
            expected_type="function",
            severity_if_missing="info",
            signature_notes="system.show_in_file_manager(path)",
            known_consumers=["11_tab_context_menu.lua", "12_ui_forge.lua"],
        ),
        APIEntry(
            id="system.exec",
            kind="function",
            module="system",
            name="exec",
            expected_type="function",
            severity_if_missing="warning",
            signature_notes="system.exec(command) -> number",
            known_consumers=["11_tab_context_menu.lua", "12_ui_forge.lua"],
        ),
    ]

    return {entry.id: entry for entry in entries}


def load_catalog(path: Optional[Union[str, Path]] = None) -> Dict[str, APIEntry]:
    """Carrega o catálogo do disco ou retorna o semente caso não exista."""
    if path is None:
        target = get_api_guard_dir() / "catalog.json"
    else:
        target = Path(path)

    if target.exists() and target.is_file():
        try:
            return APICatalogSchema.deserialize_json(target.read_text(encoding="utf-8"))
        except Exception:
            return get_default_catalog()
    return get_default_catalog()


def save_catalog(catalog: Dict[str, APIEntry], path: Optional[Union[str, Path]] = None) -> Path:
    """Salva o catálogo em JSON e exporta a versão correspondente para Lua."""
    if path is None:
        guard_dir = get_api_guard_dir()
        target_json = guard_dir / "catalog.json"
        target_lua = guard_dir / "catalog.lua"
    else:
        target_json = Path(path)
        target_lua = target_json.with_suffix(".lua")

    target_json.parent.mkdir(parents=True, exist_ok=True)
    target_json.write_text(APICatalogSchema.serialize_json(catalog), encoding="utf-8")
    target_lua.write_text(APICatalogSchema.export_to_lua(catalog), encoding="utf-8")
    return target_json


def get_api_entry(catalog: Dict[str, APIEntry], api_id: str) -> Optional[APIEntry]:
    """Consulta uma entrada no catálogo por ID."""
    return catalog.get(api_id)


def list_critical_apis(catalog: Dict[str, APIEntry]) -> List[APIEntry]:
    """Filtra apenas as APIs com severidade crítica."""
    return [e for e in catalog.values() if e.severity_if_missing == "critical"]
